apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myapp-test
images:
- digest: sha256:bb7867db07eee75e7304ad4224a9878f403d3d1ea3451c5b4eb38d71cdc7c799
  name: python-demo
  newName: harbor.shared.lab.pksdemo.net/tanzu/apps/python-demo
resources:
- python-demo-deploy.yaml
- python-demo-svc.yaml
