apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
images:
- digest: sha256:71680501c6c5ac66d3e6ac13cfb596018c7bf98ee033c74c230b7c8b441a74c4
  name: python-demo
  newName: harbor.shared.lab.pksdemo.net/tanzu/apps/python-demo
resources:
- python-demo-deploy.yaml
- python-demo-svc.yaml
- python-demo-httpproxy.yaml
