apiVersion: v1
kind: Service
metadata:
  name: python-demo-svc
  namespace: demo
  labels:
    app: python-demo
spec:
  selector:
    app: python-demo
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: NodePort
