apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: python-demo-httpproxy
  namespace: demo
spec:
  virtualhost:
    fqdn: python-demo.dev.lab.pksdemo.net
  routes:
    - conditions:
      - prefix: /
      services:
        - name: python-demo-svc
          port: 8080